export const INDUSTRY = [
	"Accounting",
	"Airlines/Aviation",
	"Alternative Dispute Resolution",
	"Alternative Medicine",
	"Animation",
	"Apparel & Fashion",
	"Architecture & Planning",
	"Arts & Crafts",
	"Automotive",
	"Aviation & Aerospace",
	"Banking",
	"Biotechnology",
	"Broadcast Media",
	"Building Materials",
	"Business Supplies & Equipment",
	"Capital Markets",
	"Chemicals",
	"Civic & Social Organization",
	"Civil Engineering",
	"Commercial Real Estate",
	"Computer & Network Security",
	"Computer Games",
	"Computer Hardware",
	"Computer Networking",
	"Computer Software",
	"Construction",
	"Consumer Electronics",
	"Consumer Goods",
	"Consumer Services",
	"Cosmetics",
	"Dairy",
	"Defense & Space",
	"Design",
	"E-learning",
	"Education Management",
	"Electrical & Electronic Manufacturing",
	"Entertainment",
	"Environmental Services",
	"Events Services",
	"Executive Office",
	"Facilities Services",
	"Farming",
	"Financial Services",
	"Fine Art",
	"Fishery",
	"Food & Beverages",
	"Food Production",
	"Fundraising",
	"Furniture",
	"Gambling & Casinos",
	"Glass, Ceramics & Concrete",
	"Government Administration",
	"Government Relations",
	"Graphic Design",
	"Health, Wellness & Fitness",
	"Higher Education",
	"Hospital & Health Care",
	"Hospitality",
	"Human Resources",
	"Import & Export",
	"Individual & Family Services",
	"Industrial Automation",
	"Information Services",
	"Information Technology & Services",
	"Insurance",
	"International Affairs",
	"International Trade & Development",
	"Internet",
	"Investment Banking",
	"Investment Management",
	"Judiciary",
	"Law Enforcement",
	"Law Practice",
	"Legal Services",
	"Legislative Office",
	"Leisure, Travel & Tourism",
	"Libraries",
	"Logistics & Supply Chain",
	"Luxury Goods & Jewelry",
	"Machinery",
	"Management Consulting",
	"Maritime",
	"Market Research",
	"Marketing & Advertising",
	"Mechanical Or Industrial Engineering",
	"Media Production",
	"Medical Device",
	"Medical Practice",
	"Mental Health Care",
	"Military",
	"Mining & Metals",
	"Motion Pictures & Film",
	"Museums & Institutions",
	"Music",
	"Nanotechnology",
	"Newspapers",
	"Non-profit Organization Management",
	"Oil & Energy",
	"Online Media",
	"Outsourcing/Offshoring",
	"Package/Freight Delivery",
	"Packaging & Containers",
	"Paper & Forest Products",
	"Performing Arts",
	"Pharmaceuticals",
	"Philanthropy",
	"Photography",
	"Plastics",
	"Political Organization",
	"Primary/Secondary Education",
	"Printing",
	"Professional Training & Coaching",
	"Program Development",
	"Public Policy",
	"Public Relations & Communications",
	"Public Safety",
	"Publishing",
	"Railroad Manufacture",
	"Ranching",
	"Real Estate",
	"Recreational Facilities & Services",
	"Religious Institutions",
	"Renewables & Environment",
	"Research",
	"Restaurants",
	"Retail",
	"Security & Investigations",
	"Semiconductors",
	"Shipbuilding",
	"Sporting Goods",
	"Sports",
	"Staffing & Recruiting",
	"Supermarkets",
	"Telecommunications",
	"Textiles",
	"Think Tanks",
	"Tobacco",
	"Translation & Localization",
	"Transportation/Trucking/Railroad",
	"Utilities",
	"Venture Capital & Private Equity",
	"Veterinary",
	"Warehousing",
	"Wholesale",
	"Wine & Spirits",
	"Wireless",
	"Writing & Editing"
];

export const US_STATE = [
	"ALABAMA",
	"ALASKA",
	"ARIZONA",
	"ARKANSAS",
	"CALIFORNIA",
	"COLORADO",
	"CONNECTICUT",
	"DELAWARE",
	"FLORIDA",
	"GEORGIA",
	"HAWAII",
	"IDAHO",
	"ILLINOIS",
	"INDIANA",
	"IOWA",
	"KANSAS",
	"KENTUCKY",
	"LOUISIANA",
	"MAINE",
	"MARYLAND",
	"MASSACHUSETTS",
	"MICHIGAN",
	"MINNESOTA",
	"MISSISSIPPI",
	"MISSOURI",
	"MONTANA",
	"NEBRASKA",
	"NEVADA",
	"NEW HAMPSHIRE",
	"NEW JERSEY",
	"NEW MEXICO",
	"NEW YORK",
	"NORTH CAROLINA",
	"NORTH DAKOTA",
	"OHIO",
	"OKLAHOMA",
	"OREGON",
	"PENNSYLVANIA",
	"RHODE ISLAND",
	"SOUTH CAROLINA",
	"SOUTH DAKOTA",
	"TENNESSEE",
	"TEXAS",
	"UTAH",
	"VERMONT",
	"VIRGINIA",
	"WASHINGTON",
	"WEST VIRGINIA",
	"WISCONSIN",
	"WYOMING"
];

export const DEGREES = ["High School", "Bachelors", "Masters", "PhD"];

export const Matches = [
	{
		id: 1,
		name: "Furby",
		degree: 1,
		linkedInUrl: "https://www.linkedin.com/company/furby",
		imageUrl:
			"https://static.businessinsider.sg/2019/03/03/5c7d63e72628982448338075.png",
		matchScore: 100,
		matchFields: ["industry"]
	},
	{
		id: 1,
		name: "Tadas Antanavicius",
		degree: 1,
		linkedInUrl: "https://www.linkedin.com/in/antanavicius/",
		imageUrl:
			"https://media.licdn.com/dms/image/C5603AQG6c6WUatDAXA/profile-displayphoto-shrink_200_200/0?e=1579737600&v=beta&t=335KWeXVQE6vL9R5w3DtHXg3ln_Wawt9YT1Ax7Xgi1o",
		matchScore: 10,
		matchFields: ["education", "location"]
	},
	{
		id: 4,
		name: "Adrian Lievano",
		degree: 1,
		linkedInUrl: "https://www.linkedin.com/in/adrianlievano/",
		imageUrl:
			"https://media.licdn.com/dms/image/C5603AQFhcCzxzbeuXA/profile-displayphoto-shrink_200_200/0?e=1579737600&v=beta&t=vcKWB5PUyHoriQp9wvvMpHJwTQVt9YMNKr-RBmObhOA",
		matchScore: 99,
		matchFields: ["experience"]
	},
	{
		id: 2,
		name: "Morgan Snyder",
		degree: 2,
		linkedInUrl: "https://www.linkedin.com/in/mosnyder/",
		imageUrl:
			"https://media.licdn.com/dms/image/C5603AQFSDThsN3EGoQ/profile-displayphoto-shrink_200_200/0?e=1579737600&v=beta&t=oMhk2F90xSR-Jhau9fe2awfe6iHe6_oLTlQJV8e300U",
		matchScore: 30,
		matchFields: ["education", "location"]
	},
	{
		id: 3,
		name: "Andrew Li",
		degree: 1,
		linkedInUrl: "https://www.linkedin.com/in/andrewli1030/",
		imageUrl:
			"https://media.licdn.com/dms/image/C4D03AQH0XJ5Nc1J7PA/profile-displayphoto-shrink_200_200/0?e=1579737600&v=beta&t=PSwTeI3igU-y_5ntri2pDojj60zyyaHnmogqeQrn_xs",
		matchScore: 28,
		matchFields: ["location"]
	},
	{
		id: 5,
		name: "Dennis Sell",
		degree: 2,
		linkedInUrl: "https://www.linkedin.com/in/selld/",
		imageUrl:
			"https://media.licdn.com/dms/image/C5603AQFOvvj_VQvjhw/profile-displayphoto-shrink_200_200/0?e=1579737600&v=beta&t=UEf_W1oyNW_y0JMGIyaVtjPSGTmoNrQWCjTMJgkxmQ0",
		matchScore: 81,
		matchFields: []
	}
];
